### ISSUE TITLE
Instead of echoing notification count, echo notification content instead.

### ISSUE THREAD

**Issue by tenten8401** [Adriani6/SpigotNotifier#9]
Title pretty much says it all. Let chrome handle the notification count and when you get a notification, just echo the actual content of the notification itself.

**Comment by Adriani6** [comment]
I have implemented this in the newest update. However I don't want to publish it (you can check it out here) since it loads the page to get the content of the notification in background and once it does that the new notification icon is reset when you enter the forums, so you'd have to manually enter spigotmc.org->alerts page.

**Comment by tenten8401** [comment]
"here"?

**Comment by Adriani6** [comment]
Here - this Github repository.
